---
title: "Replication of Study Yu & Smith (2007) by Park (2024, Psychological Science)"
author: "Replication Author[s] (contact information)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

My background is in linguistics, and my general research interests include first-language learning and language acquisition. My capstone project for the CSS program is about training machine learning models to automatically recognize various aspects of speech in children, especially when it comes to processing word boundaries and recognizing what a word actually is. While statistical word learning is not directly related to speech production, understanding how word learning works may help identify elements of speech that can be better tuned with machine learning models' word identification and boundary processing. Further understanding of statistical word learning, even in adults, may also lead to general improvements in language processing training and outcomes for machine learning models. 

Conducting this experiment will require at least 54 pictures of uncommon objects (the examples given in the original paper are "canister", "facial sauna", and "rasp"); and a matching number of pseudowords. The original paper describes these pseudoword learning targets as "broadly phonotactically plausible"; stimuli will need to be checked to ensure they are not too unusual for American English. The original paper also used a computer program to generate these pseudowords, which cuts out some possible researcher bias in handcrafting pseudowords; however, figuring out how to program a pseudoword generator myself is a little beyond me for the scope of a one-quarter research project, and stimuli will have to be either generated using Internet tools with opaque generation algorithms or subject to bias from direct human creation. Finding a program that can produce recordings of these pseudowords in a synthetic to pair with the pictures should not be difficult. Selecting the pictures may be somewhat difficult, as they should be objects that already exist so as not to further disrupt the natural learning process, but also should not be objects that participants could be expected to readily label.

The repository for this project is available [on Github](https://github.com/ucsd-psych201a/yu2007). The original paper, [Rapid Word Learning Under Uncertainty via Cross-Situational Statistics (Yu & Smith, 2007)](https://github.com/a2ypark/yu2007/tree/main/original_paper), is also available on Github. 

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

The original paper had 38 college students as participants for their experiment. 

### Materials

The original paper describes its stimuli as follows:

"The stimuli were slides containing pictures of uncommon objects (e.g., canister, facial sauna, and rasp) paired with auditorily presented pseudowords. These artificial words were generated by a computer program to sample English forms that were broadly phonotactically probable; they were produced by a synthetic female voice in monotone."

We obtained 18 pairs of images and audio files from the original paper. However, the experiment requires 54 pairs of images and audio files to complete the within-participant manipulation of learning conditions. The remaining 36 images will be selected from the [Novel Object and Unusual Name (NOUN) Database](http://www.sussex.ac.uk/wordlab/noun). The NOUN database also includes pseudowords that fit the "broadly phonotactically probable" criterion; 36 words will be selected and processed through a text-to-speech tool to create the remaining audio stimuli. 

Sixteen out of the eighteen original audio stimuli available are two-syllable pseudowords with stress on the initial syllable. Two pseudowords (numbered 6 and 10 in the set of original stimuli) are single syllables. The majority of pseudoword stimuli follow CV or CVC syllable structure, avoiding vowel onsets in both word-initial and syllable-initial positions. The stimuli also avoid highly clustered codas, with only two out of eighteen original stimuli containing syllable-final CC clusters; the other stimuli tend toward single-C codas if present, with eight stimuli featuring no word-final coda. The stimuli tend not to feature fricatives and instead generally consist of stops. There are no diphthongs or vowel hiatus in the original stimuli. The stimuli are, as reported in the paper, generally delivered in monotone.

Accordingly, the majority of newly selected stimuli should consist of two-syllable, consonant-initial pseudowords preferring CV or CVC syllables with no diphthongs or vowel hiatus; highly preferring stops over fricatives; and with consonant clustering no more complex than CC in either onset or coda positions. Where applicable, stress should fall on the first syllable. Newly selected stimuli should also be produced in monotone.

### Procedure	

The original paper's procedure is described as follows:

"To form each trial, we randomly selected several (2, 3, or 4, depending on condition) word-referent pairs from the 18 word-referent pairs for that condition; across trials in a condition, each word and referent were presented six times."
"Subjects were instructed that their task was to learn the words and referents, but they were not told that there was one referent per word. They were told that multiple words and pictures would co-occur on each trial and that their task was to figure out across trials which word went with which picture. After training in each condition, subjects received a four-alternative forced-choice test of learning. On the test, they were presented with 1 word and 4 pictures and asked to indicate the picture named by that word. The target picture and the 3 foils were all drawn from the set of 18 training pictures."

This procedure will be followed as closely as possible. It is somewhat unclear how many words were tested after a condition; the paper occasionally phrases the test as if it presented exactly one word each time, but in other sections discusses the proportion of pairs correctly discovered by participants, implying that the test after each condition covered each word. 


### Analysis Plan

The original paper features a one-tailed t-test for the number of word-referent pairs learned by participants (vs chance likelihood of correct guesses on the test after training trials). This seems to be the primary statistic concerning Experiment 1. 

The original paper does not describe data cleaning or whether any subjects withdrew or were dropped from the first experiment.

### Differences from Original Study

The original paper specifies that stimuli were presented on a 17in. computer screen; this replication experiment will not be able to standardize the screen or speaker quality. However, this should not affect the study effects as long as the user's speakers or headphones are not so poor as to prevent their ability to distinguish pseudowords. Avoiding the use of minimal pair pseudowords and specifying that participants should have quality headphones or speakers should help migitate this concern. 


### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
